### ISSUE TITLE
Play doesn't retry to establish failed database connection when starting

### ISSUE THREAD

**Issue by rusins** [flyway/flyway-play#62]
Steps to reproduce:
1. Have database server off/inaccessible.
2. Launch app
3. When connecting, the following error will be shown:
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/3919420/45881214-3b827080-bdb3-11e8-94d4-aeb781c84809.png">
(FlywaySqlException: Unable to obtain connection from database ...)

4. Turn database on
5. Refresh page / wait for a long time - the same error persists.

If flyway isn't enabled, the app will successfully reconnect to the database once it comes online.
Is there some setting I should use to tell flyway to attempt to reconnect ever so often?

Using flyway-play 5.0.0, Play 2.6.18. Tried both of these configurations:
```
db {
  nevos {
    url = "jdbc:postgresql://localhost:5432/nevos"
    user = "admin"
    password = "smth"
    driver = org.postgresql.Driver
    connectionPool = disabled
    keepAliveConnection = true
  }
}
```
or with dedicated connection pool:
```
db {
  nevos {
    url = "jdbc:postgresql://localhost:5432/nevos"
    user = "admin"
    password = "smth"
    driver = org.postgresql.Driver
    pool = hikaricp
    keepAliveConnection = true
    hikaricp {
      initializationFailTimeout = -1
      allowPoolSuspension = true
    }
  }
}
```

**Comment by tototoshi** [comment]
Probably this is impossible in Play 2.6, it will be possible from Play 2.7.

In Play, application reloading is done when source code is changed. Just changing the state of the database does not reload the application.

Or you need to call `BuildLink#forceReload` and tell sbt-plugin to reload the Play application with the next request. This is possible with the `WebCommand` used to implement the flyway-play management screen, (which is why reloading from the management screen is possible). However, `BuildLink` can not be accessed from normal application code.

I read the master code of Play, and it seems that it is possible to access the instance of `BuildLink` from application code from Play 2.7. I will try to implement it after Play 2.7 is released.
